/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_AdditionalRRMPriorityIndex_H_
#define	_AdditionalRRMPriorityIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalRRMPriorityIndex */
typedef BIT_STRING_t	 AdditionalRRMPriorityIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdditionalRRMPriorityIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdditionalRRMPriorityIndex;
asn_struct_free_f AdditionalRRMPriorityIndex_free;
asn_struct_print_f AdditionalRRMPriorityIndex_print;
asn_constr_check_f AdditionalRRMPriorityIndex_constraint;
per_type_decoder_f AdditionalRRMPriorityIndex_decode_aper;
per_type_encoder_f AdditionalRRMPriorityIndex_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalRRMPriorityIndex_H_ */
#include <asn_internal.h>
