/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HandoverRequiredIEs;
struct HandoverCommandIEs;
struct HandoverPreparationFailureIEs;
struct HandoverRequestIEs;
struct HandoverRequestAcknowledgeIEs;
struct HandoverFailureIEs;
struct HandoverNotifyIEs;
struct PathSwitchRequestIEs;
struct PathSwitchRequestAcknowledgeIEs;
struct PathSwitchRequestFailureIEs;
struct HandoverCancelIEs;
struct HandoverCancelAcknowledgeIEs;
struct E_RABSetupRequestIEs;
struct E_RABSetupResponseIEs;
struct E_RABModifyRequestIEs;
struct E_RABModifyResponseIEs;
struct E_RABReleaseCommandIEs;
struct E_RABReleaseResponseIEs;
struct E_RABReleaseIndicationIEs;
struct InitialContextSetupRequestIEs;
struct InitialContextSetupResponseIEs;
struct InitialContextSetupFailureIEs;
struct PagingIEs;
struct UEContextReleaseRequest_IEs;
struct UEContextReleaseCommand_IEs;
struct UEContextReleaseComplete_IEs;
struct UEContextModificationRequestIEs;
struct UEContextModificationResponseIEs;
struct UEContextModificationFailureIEs;
struct UERadioCapabilityMatchRequestIEs;
struct UERadioCapabilityMatchResponseIEs;
struct DownlinkNASTransport_IEs;
struct InitialUEMessage_IEs;
struct UplinkNASTransport_IEs;
struct NASNonDeliveryIndication_IEs;
struct RerouteNASRequest_IEs;
struct NASDeliveryIndicationIEs;
struct ResetIEs;
struct ResetAcknowledgeIEs;
struct ErrorIndicationIEs;
struct S1SetupRequestIEs;
struct S1SetupResponseIEs;
struct S1SetupFailureIEs;
struct ENBConfigurationUpdateIEs;
struct ENBConfigurationUpdateAcknowledgeIEs;
struct ENBConfigurationUpdateFailureIEs;
struct MMEConfigurationUpdateIEs;
struct MMEConfigurationUpdateAcknowledgeIEs;
struct MMEConfigurationUpdateFailureIEs;
struct DownlinkS1cdma2000tunnellingIEs;
struct UplinkS1cdma2000tunnellingIEs;
struct UECapabilityInfoIndicationIEs;
struct ENBStatusTransferIEs;
struct MMEStatusTransferIEs;
struct TraceStartIEs;
struct TraceFailureIndicationIEs;
struct DeactivateTraceIEs;
struct CellTrafficTraceIEs;
struct LocationReportingControlIEs;
struct LocationReportingFailureIndicationIEs;
struct LocationReportIEs;
struct OverloadStartIEs;
struct OverloadStopIEs;
struct WriteReplaceWarningRequestIEs;
struct WriteReplaceWarningResponseIEs;
struct ENBDirectInformationTransferIEs;
struct MMEDirectInformationTransferIEs;
struct ENBConfigurationTransferIEs;
struct MMEConfigurationTransferIEs;
struct KillRequestIEs;
struct KillResponseIEs;
struct PWSRestartIndicationIEs;
struct PWSFailureIndicationIEs;
struct DownlinkUEAssociatedLPPaTransport_IEs;
struct UplinkUEAssociatedLPPaTransport_IEs;
struct DownlinkNonUEAssociatedLPPaTransport_IEs;
struct UplinkNonUEAssociatedLPPaTransport_IEs;
struct E_RABModificationIndicationIEs;
struct E_RABModificationConfirmIEs;
struct UEContextModificationIndicationIEs;
struct UEContextModificationConfirmIEs;
struct UEContextSuspendRequestIEs;
struct UEContextSuspendResponseIEs;
struct UEContextResumeRequestIEs;
struct UEContextResumeResponseIEs;
struct UEContextResumeFailureIEs;
struct ConnectionEstablishmentIndicationIEs;
struct RetrieveUEInformationIEs;
struct UEInformationTransferIEs;
struct ENBCPRelocationIndicationIEs;
struct MMECPRelocationIndicationIEs;
struct SecondaryRATDataUsageReportIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_7327P0 {
	A_SEQUENCE_OF(struct HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P0_t;
typedef struct ProtocolIE_Container_7327P1 {
	A_SEQUENCE_OF(struct HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P1_t;
typedef struct ProtocolIE_Container_7327P2 {
	A_SEQUENCE_OF(struct HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P2_t;
typedef struct ProtocolIE_Container_7327P3 {
	A_SEQUENCE_OF(struct HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P3_t;
typedef struct ProtocolIE_Container_7327P4 {
	A_SEQUENCE_OF(struct HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P4_t;
typedef struct ProtocolIE_Container_7327P5 {
	A_SEQUENCE_OF(struct HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P5_t;
typedef struct ProtocolIE_Container_7327P6 {
	A_SEQUENCE_OF(struct HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P6_t;
typedef struct ProtocolIE_Container_7327P7 {
	A_SEQUENCE_OF(struct PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P7_t;
typedef struct ProtocolIE_Container_7327P8 {
	A_SEQUENCE_OF(struct PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P8_t;
typedef struct ProtocolIE_Container_7327P9 {
	A_SEQUENCE_OF(struct PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P9_t;
typedef struct ProtocolIE_Container_7327P10 {
	A_SEQUENCE_OF(struct HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P10_t;
typedef struct ProtocolIE_Container_7327P11 {
	A_SEQUENCE_OF(struct HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P11_t;
typedef struct ProtocolIE_Container_7327P12 {
	A_SEQUENCE_OF(struct E_RABSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P12_t;
typedef struct ProtocolIE_Container_7327P13 {
	A_SEQUENCE_OF(struct E_RABSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P13_t;
typedef struct ProtocolIE_Container_7327P14 {
	A_SEQUENCE_OF(struct E_RABModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P14_t;
typedef struct ProtocolIE_Container_7327P15 {
	A_SEQUENCE_OF(struct E_RABModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P15_t;
typedef struct ProtocolIE_Container_7327P16 {
	A_SEQUENCE_OF(struct E_RABReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P16_t;
typedef struct ProtocolIE_Container_7327P17 {
	A_SEQUENCE_OF(struct E_RABReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P17_t;
typedef struct ProtocolIE_Container_7327P18 {
	A_SEQUENCE_OF(struct E_RABReleaseIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P18_t;
typedef struct ProtocolIE_Container_7327P19 {
	A_SEQUENCE_OF(struct InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P19_t;
typedef struct ProtocolIE_Container_7327P20 {
	A_SEQUENCE_OF(struct InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P20_t;
typedef struct ProtocolIE_Container_7327P21 {
	A_SEQUENCE_OF(struct InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P21_t;
typedef struct ProtocolIE_Container_7327P22 {
	A_SEQUENCE_OF(struct PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P22_t;
typedef struct ProtocolIE_Container_7327P23 {
	A_SEQUENCE_OF(struct UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P23_t;
typedef struct ProtocolIE_Container_7327P24 {
	A_SEQUENCE_OF(struct UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P24_t;
typedef struct ProtocolIE_Container_7327P25 {
	A_SEQUENCE_OF(struct UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P25_t;
typedef struct ProtocolIE_Container_7327P26 {
	A_SEQUENCE_OF(struct UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P26_t;
typedef struct ProtocolIE_Container_7327P27 {
	A_SEQUENCE_OF(struct UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P27_t;
typedef struct ProtocolIE_Container_7327P28 {
	A_SEQUENCE_OF(struct UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P28_t;
typedef struct ProtocolIE_Container_7327P29 {
	A_SEQUENCE_OF(struct UERadioCapabilityMatchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P29_t;
typedef struct ProtocolIE_Container_7327P30 {
	A_SEQUENCE_OF(struct UERadioCapabilityMatchResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P30_t;
typedef struct ProtocolIE_Container_7327P31 {
	A_SEQUENCE_OF(struct DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P31_t;
typedef struct ProtocolIE_Container_7327P32 {
	A_SEQUENCE_OF(struct InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P32_t;
typedef struct ProtocolIE_Container_7327P33 {
	A_SEQUENCE_OF(struct UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P33_t;
typedef struct ProtocolIE_Container_7327P34 {
	A_SEQUENCE_OF(struct NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P34_t;
typedef struct ProtocolIE_Container_7327P35 {
	A_SEQUENCE_OF(struct RerouteNASRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P35_t;
typedef struct ProtocolIE_Container_7327P36 {
	A_SEQUENCE_OF(struct NASDeliveryIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P36_t;
typedef struct ProtocolIE_Container_7327P37 {
	A_SEQUENCE_OF(struct ResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P37_t;
typedef struct ProtocolIE_Container_7327P38 {
	A_SEQUENCE_OF(struct ResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P38_t;
typedef struct ProtocolIE_Container_7327P39 {
	A_SEQUENCE_OF(struct ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P39_t;
typedef struct ProtocolIE_Container_7327P40 {
	A_SEQUENCE_OF(struct S1SetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P40_t;
typedef struct ProtocolIE_Container_7327P41 {
	A_SEQUENCE_OF(struct S1SetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P41_t;
typedef struct ProtocolIE_Container_7327P42 {
	A_SEQUENCE_OF(struct S1SetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P42_t;
typedef struct ProtocolIE_Container_7327P43 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P43_t;
typedef struct ProtocolIE_Container_7327P44 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P44_t;
typedef struct ProtocolIE_Container_7327P45 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P45_t;
typedef struct ProtocolIE_Container_7327P46 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P46_t;
typedef struct ProtocolIE_Container_7327P47 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P47_t;
typedef struct ProtocolIE_Container_7327P48 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P48_t;
typedef struct ProtocolIE_Container_7327P49 {
	A_SEQUENCE_OF(struct DownlinkS1cdma2000tunnellingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P49_t;
typedef struct ProtocolIE_Container_7327P50 {
	A_SEQUENCE_OF(struct UplinkS1cdma2000tunnellingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P50_t;
typedef struct ProtocolIE_Container_7327P51 {
	A_SEQUENCE_OF(struct UECapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P51_t;
typedef struct ProtocolIE_Container_7327P52 {
	A_SEQUENCE_OF(struct ENBStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P52_t;
typedef struct ProtocolIE_Container_7327P53 {
	A_SEQUENCE_OF(struct MMEStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P53_t;
typedef struct ProtocolIE_Container_7327P54 {
	A_SEQUENCE_OF(struct TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P54_t;
typedef struct ProtocolIE_Container_7327P55 {
	A_SEQUENCE_OF(struct TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P55_t;
typedef struct ProtocolIE_Container_7327P56 {
	A_SEQUENCE_OF(struct DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P56_t;
typedef struct ProtocolIE_Container_7327P57 {
	A_SEQUENCE_OF(struct CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P57_t;
typedef struct ProtocolIE_Container_7327P58 {
	A_SEQUENCE_OF(struct LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P58_t;
typedef struct ProtocolIE_Container_7327P59 {
	A_SEQUENCE_OF(struct LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P59_t;
typedef struct ProtocolIE_Container_7327P60 {
	A_SEQUENCE_OF(struct LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P60_t;
typedef struct ProtocolIE_Container_7327P61 {
	A_SEQUENCE_OF(struct OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P61_t;
typedef struct ProtocolIE_Container_7327P62 {
	A_SEQUENCE_OF(struct OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P62_t;
typedef struct ProtocolIE_Container_7327P63 {
	A_SEQUENCE_OF(struct WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P63_t;
typedef struct ProtocolIE_Container_7327P64 {
	A_SEQUENCE_OF(struct WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P64_t;
typedef struct ProtocolIE_Container_7327P65 {
	A_SEQUENCE_OF(struct ENBDirectInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P65_t;
typedef struct ProtocolIE_Container_7327P66 {
	A_SEQUENCE_OF(struct MMEDirectInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P66_t;
typedef struct ProtocolIE_Container_7327P67 {
	A_SEQUENCE_OF(struct ENBConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P67_t;
typedef struct ProtocolIE_Container_7327P68 {
	A_SEQUENCE_OF(struct MMEConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P68_t;
typedef struct ProtocolIE_Container_7327P69 {
	A_SEQUENCE_OF(struct KillRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P69_t;
typedef struct ProtocolIE_Container_7327P70 {
	A_SEQUENCE_OF(struct KillResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P70_t;
typedef struct ProtocolIE_Container_7327P71 {
	A_SEQUENCE_OF(struct PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P71_t;
typedef struct ProtocolIE_Container_7327P72 {
	A_SEQUENCE_OF(struct PWSFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P72_t;
typedef struct ProtocolIE_Container_7327P73 {
	A_SEQUENCE_OF(struct DownlinkUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P73_t;
typedef struct ProtocolIE_Container_7327P74 {
	A_SEQUENCE_OF(struct UplinkUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P74_t;
typedef struct ProtocolIE_Container_7327P75 {
	A_SEQUENCE_OF(struct DownlinkNonUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P75_t;
typedef struct ProtocolIE_Container_7327P76 {
	A_SEQUENCE_OF(struct UplinkNonUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P76_t;
typedef struct ProtocolIE_Container_7327P77 {
	A_SEQUENCE_OF(struct E_RABModificationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P77_t;
typedef struct ProtocolIE_Container_7327P78 {
	A_SEQUENCE_OF(struct E_RABModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P78_t;
typedef struct ProtocolIE_Container_7327P79 {
	A_SEQUENCE_OF(struct UEContextModificationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P79_t;
typedef struct ProtocolIE_Container_7327P80 {
	A_SEQUENCE_OF(struct UEContextModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P80_t;
typedef struct ProtocolIE_Container_7327P81 {
	A_SEQUENCE_OF(struct UEContextSuspendRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P81_t;
typedef struct ProtocolIE_Container_7327P82 {
	A_SEQUENCE_OF(struct UEContextSuspendResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P82_t;
typedef struct ProtocolIE_Container_7327P83 {
	A_SEQUENCE_OF(struct UEContextResumeRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P83_t;
typedef struct ProtocolIE_Container_7327P84 {
	A_SEQUENCE_OF(struct UEContextResumeResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P84_t;
typedef struct ProtocolIE_Container_7327P85 {
	A_SEQUENCE_OF(struct UEContextResumeFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P85_t;
typedef struct ProtocolIE_Container_7327P86 {
	A_SEQUENCE_OF(struct ConnectionEstablishmentIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P86_t;
typedef struct ProtocolIE_Container_7327P87 {
	A_SEQUENCE_OF(struct RetrieveUEInformationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P87_t;
typedef struct ProtocolIE_Container_7327P88 {
	A_SEQUENCE_OF(struct UEInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P88_t;
typedef struct ProtocolIE_Container_7327P89 {
	A_SEQUENCE_OF(struct ENBCPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P89_t;
typedef struct ProtocolIE_Container_7327P90 {
	A_SEQUENCE_OF(struct MMECPRelocationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P90_t;
typedef struct ProtocolIE_Container_7327P91 {
	A_SEQUENCE_OF(struct SecondaryRATDataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_7327P91_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P76;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P76_153[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P77;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P77_155[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P78;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P78_157[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P79;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P79_159[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P80;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P80_161[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P81;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P81_163[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P82;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P82_165[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P83;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P83_167[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P84;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P84_169[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P85;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P85_171[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P86;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P86_173[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P87;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P87_175[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P88;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P88_177[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P89;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P89_179[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P90;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P90_181[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_7327P91;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_7327P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_7327P91_183[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_7327P91_constr_183;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
