/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_H_
#define	_ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiveStatusOfULPDCPSDUsPDCP-SNlength18 */
typedef BIT_STRING_t	 ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReceiveStatusOfULPDCPSDUsPDCP_SNlength18;
asn_struct_free_f ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_free;
asn_struct_print_f ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_print;
asn_constr_check_f ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_constraint;
per_type_decoder_f ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_decode_aper;
per_type_encoder_f ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiveStatusOfULPDCPSDUsPDCP_SNlength18_H_ */
#include <asn_internal.h>
