/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_RequestTypeAdditionalInfo_H_
#define	_RequestTypeAdditionalInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RequestTypeAdditionalInfo {
	RequestTypeAdditionalInfo_includePSCell	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RequestTypeAdditionalInfo;

/* RequestTypeAdditionalInfo */
typedef long	 RequestTypeAdditionalInfo_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RequestTypeAdditionalInfo_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RequestTypeAdditionalInfo;
extern const asn_INTEGER_specifics_t asn_SPC_RequestTypeAdditionalInfo_specs_1;
asn_struct_free_f RequestTypeAdditionalInfo_free;
asn_struct_print_f RequestTypeAdditionalInfo_print;
asn_constr_check_f RequestTypeAdditionalInfo_constraint;
per_type_decoder_f RequestTypeAdditionalInfo_decode_aper;
per_type_encoder_f RequestTypeAdditionalInfo_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestTypeAdditionalInfo_H_ */
#include <asn_internal.h>
