/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_UE_Usage_Type_H_
#define	_UE_Usage_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-Usage-Type */
typedef long	 UE_Usage_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UE_Usage_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UE_Usage_Type;
asn_struct_free_f UE_Usage_Type_free;
asn_struct_print_f UE_Usage_Type_print;
asn_constr_check_f UE_Usage_Type_constraint;
per_type_decoder_f UE_Usage_Type_decode_aper;
per_type_encoder_f UE_Usage_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Usage_Type_H_ */
#include <asn_internal.h>
