/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "36413-g10.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER`
 */

#ifndef	_UEUserPlaneCIoTSupportIndicator_H_
#define	_UEUserPlaneCIoTSupportIndicator_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEUserPlaneCIoTSupportIndicator {
	UEUserPlaneCIoTSupportIndicator_supported	= 0
	/*
	 * Enumeration is extensible
	 */
} e_UEUserPlaneCIoTSupportIndicator;

/* UEUserPlaneCIoTSupportIndicator */
typedef long	 UEUserPlaneCIoTSupportIndicator_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UEUserPlaneCIoTSupportIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UEUserPlaneCIoTSupportIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_UEUserPlaneCIoTSupportIndicator_specs_1;
asn_struct_free_f UEUserPlaneCIoTSupportIndicator_free;
asn_struct_print_f UEUserPlaneCIoTSupportIndicator_print;
asn_constr_check_f UEUserPlaneCIoTSupportIndicator_constraint;
per_type_decoder_f UEUserPlaneCIoTSupportIndicator_decode_aper;
per_type_encoder_f UEUserPlaneCIoTSupportIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UEUserPlaneCIoTSupportIndicator_H_ */
#include <asn_internal.h>
